name: CI-CD AdventureWorks

on:
  push:
    branches:
      - main

jobs:
  deploy-sql:
    runs-on:  self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQLCMD tools
        run: choco install sqlcmd -y

      - name: Run SQL scripts using Windows Authentication
        run: sqlcmd -S localhost -d AdventureWorks -E -i instawdb.sql
